### ISSUE TITLE
gitHub breaks with FFPS

### ISSUE THREAD

**Issue by akseiya** [simeononsecurity/FireFox-Privacy-Script#11]
# Describe the bug

When opening a gitHub repo (like [Privacy Script's](https://github.com/simeononsecurity/FireFox-Privacy-Script) or one of my own), only header and footer loads, nothing shows up in the main section.

# To Reproduce
1. Go to https://github.com/simeononsecurity/FireFox-Privacy-Script
2. It does open with 'Code' tab highlighted, but nothing shows up below.

# Expected behavior
Code view of the repo shows below the headers.

# Screenshots
### Current view in Firefox with Privacy Script:

![Screenshot from 2024-02-01 13-23-23](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/2485560/4debb109-8926-4c31-bc18-5f11fbf34038)

---

### Current view in LibreWolf:

![Screenshot from 2024-02-01 13-25-17](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/2485560/efdc8ae1-b07a-4c6e-bf14-0998b647d804)

# Desktop
 - OS: 64bit Pop!_OS 22.04 LTS
 - gnome 42.9 on Wayland and Xorg

# **Additional context**
* the same privacy measure breaks BitBucket:
  > We tried to load scripts but something went wrong.
  > 
  > Please make sure that your network settings allow you to download scripts from the following domain:
  > https://aid-frontend.prod.atl-paas.net

* I can see that the repo contains Mozilla.cfg file but the shell script doesn't seem to try copying it anywhere, could that have an impact? I don't even know where the file should sit...

**Comment by simeononsecurity** [comment]
Besides the cfg issue it should be functioning identically on windows and we're not having any issues. The cfg should only restrict firefox more. 
Though we did fix that now just here https://github.com/simeononsecurity/FireFox-Privacy-Script/commit/44a4b6cdb3b8f955403deed502feecca2c539126


We'll need to test this further. Unfortunately we don't have automated testing for this repo set up yet, not do I think we will. 
So that may take some time. 
Be sure to make sure you whitelist bitbucket and firefox in umatrix. 
Or remove umatrix in its entirety.
You'll have to fork this repo and remove the extension .xpi and modify the policies.json to make sure it doesn't auto install again. 
Umatrix will get in the way a lot if you're not used to using it. It by default blocks almost all javascript on the web. 


Anyways please try rerunning the script again and let us know if it solves your issue or not.

**Comment by akseiya** [comment]
Thank you for the response!

I fixed the .cfg issue manually. BTW, the file in your `./Files` is called `mozilla.cfg` while the `autoconfig.js` has `pref("general.config.filename", "firefox.cfg");`, so in the end I symlinked the mozilla.cfg as firefox.cfg which is when Firefox finally stopped asking to become the default browser.
* note: I doublechecked and relinked `mozilla.cfg` as `mozilla.cfg`, Firefox reads it regardless of `firefox.cfg` value in `autoconfig.js`, perhaps a fallback.

umatrix exceptions did fix my gitHub/bitBucket woes, thank you!

Generally I thought perhaps I could help.

I am a Linux boi and the Linux install script confused me a bit, like:
* why a series of `cp $dir/*` instead of `cp -rv ./Files /lib/firefox`?
  * it would copy all files and list what it copied.
  * `cp` can also be configured to override pre-existing content or not in recursive
    mode IIRC.
* why copying at all instead of symlinks? With a pull hook `git pull` could be all user needs to update FF with newest privacy tweaks;
* I would also probably rename `RED()` to `die()` and
  1. `echo` to `>&2`
  2. do `exit 1` in `die()` itself so that another Linux boi like me could call this from within another script with expected plugability

Also, I'm a test engineer.

If you think I could be of use, please do ping me via email (in my profile),

**Comment by simeononsecurity** [comment]
> note: I doublechecked and relinked mozilla.cfg as mozilla.cfg, Firefox reads it regardless of firefox.cfg value in autoconfig.js, perhaps a fallback.

yeah that is a carry over, this script isn't nearly as actively maintained as some of our others.  should be fixed now, good catch. 

>    why a series of cp $dir/* instead of cp -rv ./Files /lib/firefox?
>        it would copy all files and list what it copied.
>        cp can also be configured to override pre-existing content or not in recursive
>        mode IIRC.

What you're talking about would be more optimal sure. But it's more or less a readability enhancement than a functional one. 

>    why copying at all instead of symlinks? With a pull hook git pull could be all user needs to update FF with newest privacy tweaks;

We design all of our scripts to be functional offline wherever possible.
Additionally these privacy tweaks, especially for Firefox, don't update all that often if at all.


>    I would also probably rename RED() to die() and
>        echo to >&2
>        do exit 1 in die() itself so that another Linux boi like me could call this from within another script with expected plugability

We always expected this script to basically be a one off. With that in mind we didn't expect it to be called from other scripts. However we do like the idea and have implemented it.
