### ISSUE TITLE
Disable Web Audio API causes issue while use extension in Firefox

### ISSUE THREAD

**Issue by dennyamarojr** [simeononsecurity/FireFox-Privacy-Script#12]
**Describe the bug**
After enable the following configuration from the project into the browser, we start seeing a few issues with some extensions that uses this feature to work.
 // Disable Web Audio API
pref("dom.webaudio.enabled", false);

**To Reproduce**
1. Go to 'https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/'
2. Install the extension 'Enhancer for YouTube by Maxime RF'
3. Go to YouTube and enable boost volume
4. See the bug

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Mozilla Firefox
 - Version [122]

**Additional context**
This issue is only for additional information for the new users that will be using the mozilla.cfg from the project and also to help the developer of the project has a direction to possible issues that could be related to the same issue I got when enable this setting.

**Comment by simeononsecurity** [comment]
> **Describe the bug** After enable the following configuration from the project into the browser, we start seeing a few issues with some extensions that uses this feature to work. // Disable Web Audio API pref("dom.webaudio.enabled", false);
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to 'https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/'
> 
>     2. Install the extension 'Enhancer for YouTube by Maxime RF'
> 
>     3. Go to YouTube and enable boost volume
> 
>     4. See the bug
> 
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 11
> 
>     * Browser Mozilla Firefox
> 
>     * Version [122]
> 
> 
> **Additional context** This issue is only for additional information for the new users that will be using the mozilla.cfg from the project and also to help the developer of the project has a direction to possible issues that could be related to the same issue I got when enable this setting.

This is just one of the things you have to learn to deal with if you want your browser to be more private.
AudioContext fingerprinting is a thing which you can test at https://coveryourtracks.eff.org/
If this is something you can't live without, feel free to change it on your system. But unfortunately to change in this repo would go against what this repo's purpose is.

There are counter arguments to every privacy configuration, however the main sources we trust for this repo recommend disabling it. So we're keeping it for now. 

Thanks for your submission @dennyamarojr
