### ISSUE TITLE
ChatGPT

### ISSUE THREAD

**Issue by no1etal** [simeononsecurity/FireFox-Privacy-Script#14]
How does the script interfere with ChatGPT website?  
Since running the script, I cannot use the website to full extent; prompts cannot be sent over. Is there a particular setting that needs to be toggled or enabled for the website to run?

What are your experiences?

**Comment by simeononsecurity** [comment]
> How does the script interfere with ChatGPT website? Since running the script, I cannot use the website to full extent; prompts cannot be sent over. Is there a particular setting that needs to be toggled or enabled for the website to run?
> 
> What are your experiences?

Works fine for us over here. Try disabling adblock and privacy badger.

**Comment by no1etal** [comment]
Is there anything else that script does to the Firefox that might affect it? I have disabled all of the plugins. It also does not work on Librewolf without any plugins added. Works on Vivaldi though.

**Comment by simeononsecurity** [comment]
> Is there anything else that script does to the Firefox that might affect it? I have disabled all of the plugins. It also does not work on Librewolf without any plugins added. Works on Vivaldi though.

If you've truely disabled all the plugins, not that I can think of.
I've got it working myself right now with no issues.
