### ISSUE TITLE
How to Uninstall?

### ISSUE THREAD

**Issue by Numerosityy** [simeononsecurity/FireFox-Privacy-Script#15]
I'm trying to remove the 3 extensions this script installs: Privacy Badger, uMatrix, and the Cookie Remover extensions. They are redundant for me and I don't need them. However even after manually deleting the extension files from the extensions folder, they reinstall. How can I prevent this from happening?

**Comment by simeononsecurity** [comment]
> I'm trying to remove the 3 extensions this script installs: Privacy Badger, uMatrix, and the Cookie Remover extensions. They are redundant for me and I don't need them. However even after manually deleting the extension files from the extensions folder, they reinstall. How can I prevent this from happening?

Go to your firefox configuration folder
and remove the following file https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/Files/distribution/policies.json to remove the extensions that auto install.

**Comment by Numerosityy** [comment]
Thanks for the help. Does this script edit any settings with WebAssembly or WebGL? I've noticed my settings being undid as soon as I restart Firefox.

**Comment by simeononsecurity** [comment]
> Thanks for the help. Does this script edit any settings with WebAssembly or WebGL? I've noticed my settings being undid as soon as I restart Firefox.

The vast majority of configurations are in https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/Files/mozilla.cfg

Please take care to review scripts before running random scripts online. 
If you skimmed or searched, you would've been able to determine this yourself ;)
https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/3b9e545e6353542fd313cd2de9af21ca1bb01fe9/Files/mozilla.cfg#L204

**Comment by Numerosityy** [comment]
Fair points, I was just recommended this and I had no clue what I was doing. With enough digging I fixed everything though. Sorry for being an annoyance

**Comment by erifneerg** [comment]
I'm on osx 14.6.1 and I've trying to do everything to remove these settlings  as it was was causing more issue with some extension. I tried everything to remove the settings/folders/etc but the extension from this still install on a clean install.

**Comment by simeononsecurity** [comment]
> I'm on osx 14.6.1 and I've trying to do everything to remove these settlings as it was was causing more issue with some extension. I tried everything to remove the settings/folders/etc but the extension from this still install on a clean install.

Go into your mac and find the files the script installed in

```
    preferences_dir="/Applications/Firefox.app/Contents/Resources/defaults/pref/"
    extensions_dir="/Applications/Firefox.app//Contents/Resources/browser/features/"
    config_dir="/Applications/Firefox.app/Contents/Resources/"

    checkInstall

    rm /Library/Preferences/org.mozilla.firefox.plist
    defaults import /Library/Preferences/org.mozilla.firefox ./Files/distribution/org.mozilla.firefox.plist
  ```
