### ISSUE TITLE
Addons update loop

### ISSUE THREAD

**Issue by Rehazz** [simeononsecurity/FireFox-Privacy-Script#2]
Hello a good day,

I user your Optimize, Harden, and Debloat Windows 10 Deployments and
after each restart of the firefox, the old versions of all Addons are installed.
Ublock Orgin for example needs a browser restart to be properly updated to the current version.
Ist it possible to update All Addon with the script directly from the beginning all addons to the current versions?
Or Is there a solution how to change this after every system restart instead of every browser restart?

And another question. Normally i still use the https://github.com/arkenfox/user.js
Is there a simple solution to integrate it in the firefox profile?

Translated with www.DeepL.com/Translator (free version)

**Comment by simeononsecurity** [comment]
The addons are declared [here](https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/Files/distribution/policies.json), were possible it's defined to download the latest extensions and install those.  

When you run the script, remove the files in the equivalent [file path](https://github.com/simeononsecurity/FireFox-Privacy-Script/tree/master/Files/distribution/extensions) and see if this resolves your issue at least partially.

**Comment by simeononsecurity** [comment]
Fixed by setting the plugin urls to be all the dynamic latest
