### ISSUE TITLE
add a few tweaks

### ISSUE THREAD

**Issue by Obegg** [simeononsecurity/FireFox-Privacy-Script#3]
I have a few suggestions to add to the script.

Set to false:
```
default-browser-agent.enabled
browser.newtabpage.activity-stream.feeds.telemetry
browser.newtabpage.activity-stream.telemetry
browser.ping-centre.telemetry
datareporting.healthreport.service.enabled
devtools.onboarding.telemetry.logged
```

Information from https://github.com/K3V1991/Disable-Firefox-Telemetry-and-Data-Collection

Additional information: https://gist.github.com/0XDE57/fbd302cef7693e62c769

**Comment by simeononsecurity** [comment]
Looking into it some of these changes are redundant based on the other config options that have been set. 
However I see no reason I can't add them.
