### ISSUE TITLE
remove https-everywhere policy

### ISSUE THREAD

**Issue by Obegg** [simeononsecurity/FireFox-Privacy-Script#4]
According to this: https://www.eff.org/https-everywhere/set-https-default-your-browser
> You no longer need HTTPS Everywhere to set HTTPS by default! Major browsers now offer native support for an HTTPS only mode.
>

**Comment by simeononsecurity** [comment]
I'm unsure how this will work for internal services where I feel it's better to be warned about HTTPS not being available vs just blocking all non https traffic.
I've enabled this for now. But Ill do some more testing in the future
