### ISSUE TITLE
Install/Use instructions please

### ISSUE THREAD

**Issue by Mrsash2020** [simeononsecurity/FireFox-Privacy-Script#5]
Sorry can anyone add instructions to how to use this please. Also where do I find what it does in detail?

thanks

**Comment by simeononsecurity** [comment]
> Sorry can anyone add instructions to how to use this please. Also where do I find what it does in detail?
> 
> thanks

Once running, you'd use your browser like normal with one exception. You now have containers.
Using the firefox containers extension allows you to separate cookies and identities from being tracked across sites.
This is a third party extension and we don't feel the need to reinvent the wheel and explain how to use it. Look it up on the firefox extension store for more details.


Additionally all the changes this makes are either documented or self explanatory. 
#### configurations
https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/Files/mozilla.cfg
#### extensions
https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/Files/distribution/policies.json

Additionally these are not changes we just came up with on our own. They are changes that are suggested to do manually by organizations like [PrivacyTools.io](https://www.privacytools.io/browsers/#about_config) and [ffprofile](https://ffprofile.com/) 
These changes cover suggested browser extentions, blocking telemetry, disabling 3rd-party cookies, disabling trackers, etc.
