### ISSUE TITLE
Addon/compatibility for mobile android firefox

### ISSUE THREAD

**Issue by Doubs115** [simeononsecurity/FireFox-Privacy-Script#6]
**Is your feature request related to a problem? Please describe.**
As it stands there doesn't seem to be a way to install this script into firefox on mobile.

**Describe the solution you'd like**
Maybe if it could be made into a plugin or addon it might be easier to install or make. Otherwise I don't know coding that well so I couldn't say.

**Describe alternatives you've considered**
There arn't a lot of alternatives, using tor maybe. But tor can be slow and for a decent many people it is overkill. Don't get me wrong more privacy/security is good but that trade off might not be worth for some.

**Additional context**
The reason I bring this up is because it was recomended by chris titus tech that standard firefox is great but with this script it's almost as good as it gets. However a lot of people including myself use mobile browsers often.

So if this could be made to work with it that would benifit a lot of people that previously didn't have access.

**Comment by simeononsecurity** [comment]
> **Is your feature request related to a problem? Please describe.** As it stands there doesn't seem to be a way to install this script into firefox on mobile.
> 
> **Describe the solution you'd like** Maybe if it could be made into a plugin or addon it might be easier to install or make. Otherwise I don't know coding that well so I couldn't say.
> 
> **Describe alternatives you've considered** There arn't a lot of alternatives, using tor maybe. But tor can be slow and for a decent many people it is overkill. Don't get me wrong more privacy/security is good but that trade off might not be worth for some.
> 
> **Additional context** The reason I bring this up is because it was recomended by chris titus tech that standard firefox is great but with this script it's almost as good as it gets. However a lot of people including myself use mobile browsers often.
> 
> So if this could be made to work with it that would benifit a lot of people that previously didn't have access.

Unfortunately there is no way to make this work on mobile. 
Your best bet is to configure the settings described in the config manually. Or if your threat model allows, run this script on a pc that is signed into firefox sync, and sync the settings to mobile. Otherwise just use Firefox Focus and add Ublock Origin. That'll get you most of the way there.

**Comment by Doubs115** [comment]
@simeononsecurity So I did the sync method because it's seems fine to me. How would I check to make sure it applied?
This probably goes for the script regardless of the way I installed it. Either just on windows or windows and mobile.
Also, it might be nice to add to the instructions as a verification step.

**Comment by simeononsecurity** [comment]
> @simeononsecurity So I did the sync method because it's seems fine to me. How would I check to make sure it applied? This probably goes for the script regardless of the way I installed it. Either just on windows or windows and mobile. Also, it might be nice to add to the instructions as a verification step.

Just have to go into your mobile settings and check if it synced. It's all manual.
