### ISSUE TITLE
issue when trying to open

### ISSUE THREAD

**Issue by pizzav-xyz** [simeononsecurity/FireFox-Privacy-Script#8]
**Describe the bug**
when i run .\sos-firefoxprivacy.ps1 in windows powershell it just opens it in notepad

**To Reproduce**
1. open terminal
2. cd to the folder
3. type .\sos-firefoxprivacy.ps1 and press enter

**Expected behavior**
it runs code

**Screenshots**
![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/103120356/de78a84f-cd5e-4a4a-9ecd-de301718e433)

**Desktop (please complete the following information):**
 - OS: windows 11 
 - Browser firefox
 - Version latest

**Additional context**

**Comment by simeononsecurity** [comment]
@kittenvr 
It is a .ps1 file. You should launch it from powershell, not cmd.

**Comment by pizzav-xyz** [comment]
> @kittenvr It is a .ps1 file. You should launch it from powershell, not cmd.



> @kittenvr It is a .ps1 file. You should launch it from powershell, not cmd.

then i get this 
![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/103120356/9d96a1c0-6244-4555-90dd-4443dca2b295)

**Comment by simeononsecurity** [comment]
Run `Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass`

**Comment by pizzav-xyz** [comment]
> Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/103120356/3d1a0cd8-db4b-443a-aa7b-87f3bb840355)

**Comment by simeononsecurity** [comment]
Run `Set-ExecutionPolicy -ExecutionPolicy Unrestricted` then.

**Comment by pizzav-xyz** [comment]
> Run `Set-ExecutionPolicy -ExecutionPolicy Unrestricted` then.

![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/103120356/ef2240d2-5efa-4b1a-bb5c-cddcbeab782a)

**Comment by simeononsecurity** [comment]
@kittenvr Seems your computer doesn't have the default execution policy applied to it.

Try the following
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force
```
```
powershell -ExecutionPolicy Bypass -File "C:\Path\To\Your\Script.ps1"
```

**Comment by pizzav-xyz** [comment]
> @kittenvr Seems your computer doesn't have the default execution policy applied to it.
> 
> Try the following
> 
> ```powershell
> Set-ExecutionPolicy Bypass -Scope Process -Force
> ```
> 
> ```
> powershell -ExecutionPolicy Bypass -File "C:\Path\To\Your\Script.ps1"
> ```

![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/103120356/05c6b7f6-7cdf-4646-92df-d2e8e8665d81)

**Comment by simeononsecurity** [comment]
Try the same commands but use unrestricted instead of bypass. I've done this thousands of times and I'm not sure why your system isn't cooperating. Also try downloading the latest ps1 file

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1
