### ISSUE TITLE
PowerShell Script does not run due to spelling error  "-Forcw" instead or "-Force"

### ISSUE THREAD

**Issue by ZachHolmesDev** [simeononsecurity/FireFox-Privacy-Script#9]
**Describe the bug**
PowerShell Script in the readme does not run due to spelling error 

 "-Forcw" is spelt incorrectly instead of "-Force"

**To Reproduce**
Run the Script

**Comment by simeononsecurity** [comment]
Fixed in https://github.com/simeononsecurity/FireFox-Privacy-Script/commit/887ad4423149595a213b851604ee8dc195254be4
